[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.dev]
codegen-units = 1
lto = true
opt-level = 'z'
panic = "abort"
strip = true

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = "abort"
strip = true

[dependencies]
